name: Deno-SQL-CI

on: [push, pull_request]

jobs:
  build:
    name: deno-sql tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.x
      - run: deno test
